# Generated by Django 5.0.4 on 2024-05-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('evenement culturelle', 'evenement culturelle'), ('evnement sportif', 'evenement sportif')], default='not specified', max_length=100),
        ),
    ]
