# Generated by Django 5.0.4 on 2024-05-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categorie',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
