# Generated by Django 5.0.4 on 2024-05-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Touristes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='touriste',
            table='Touriste',
        ),
    ]
