# Generated by Django 5.0.4 on 2024-05-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hebergement',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='hebergement',
            table='Hebergement',
        ),
    ]
